config/routes.rb
AkatusDemo::Application.routes.draw do

  get  'api'        => 'checkout#api',        :as => :api
  post 'api/pay'    => 'checkout#api_pay',    :as => :api_pay

  get 'formulario' => 'checkout#form',       :as => :form
  get 'javascript' => 'checkout#javascript', :as => :javascript

  post 'api/pay/boleto'      => 'api_checkout#pay_with_boleto',      :as => :api_pay_with_boleto
  post 'api/pay/eft'         => 'api_checkout#pay_with_eft',         :as => :api_pay_with_eft
  post 'api/pay/credit_card' => 'api_checkout#pay_with_credit_card', :as => :api_pay_with_credit_card

  # You can have the root of your site routed with "root"
  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController

  def api
    set_api_cart
    @payment_options_with_installments = Rails.cache.fetch('payment') do
      Akatus::Services::PaymentOptions.available_with_installments(@cart)
    end
  end

  def api_pay

    set_api_cart
    @cart.payer = YAML.load_file("#{Rails.root}/data/payers.yml").with_indifferent_access[:payers][:payer1]

    if params[:payment_code] == 'boleto'
      @cart.payment_method = Akatus::BoletoBancario.new
      view = 'boleto'
    elsif params[:payment_code][/\Acartao/]
      opts = { brand: params[:payment_code] }.merge(params[:credit_card])
      @cart.payment_method = Akatus::CreditCard.new(opts)
      view = 'credit_card'
    elsif params[:payment_code][/\Atef/]
      @cart.payment_method = Akatus::ElectronicFundsTransfer.new(brand: params[:payment_code])
      view = 'eft'
    else
      raise "Unknown payment code: #{params[:payment_code]}"
    end

    Akatus::Services::Transaction.create(@cart)

    render "checkout/api/#{view}"

  end

  def form
    @cart = YAML.load_file("#{Rails.root}/data/form_carts.yml").with_indifferent_access[:carts][:default]
  end

  def javascript
  end

  private

  def set_api_cart
    @cart = YAML.load_file("#{Rails.root}/data/api_carts.yml").with_indifferent_access[:carts][:cart1]

    @cart.items.each do |item|
      item.price = BigDecimal.new(item.price)
    end

    @cart.discount = BigDecimal.new(@cart.discount)
    @cart.shipping_cost = BigDecimal.new(@cart.shipping_cost)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/checkout/api.html.erb
<div class="large-12 columns">
  <h1>Finalizar pedido</h1>
  <h2>Resumo do seu pedido</h2>
  <table style="width: 100%;">
    <thead>
      <tr>
        <th>Produto</th>
        <th>Quantidade</th>
        <th>Preço unitário</th>
        <th>Preço total</th>
      </tr>
    </thead>
    <tbody>
      <% @cart.items.each do |item| %>
        <tr>
          <td><%= item.description %></td>
          <td><%= item.quantity %></td>
          <td><%= number_to_currency(item.price) %></td>
          <td><%= number_to_currency(item.price * item.quantity) %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="3">Frete</td>
        <td><%= number_to_currency(@cart.shipping_cost) %></td>
      </tr>
      <tr>
        <td colspan="3">Desconto</td>
        <td><%= number_to_currency(@cart.discount) %></td>
      </tr>
      <tr>
        <td colspan="3">Total</td>
        <td><%= number_to_currency(@cart.total_amount) %></td>
      </tr>
    </tfoot>
  </table>
  <h2>Formas de pagamento</h2>

  <% @payment_options_with_installments.each do |group, details| %>
    <h3><%= details[:name] %></h3>

    <% if group != :credit_card %>
      <% details[:options].each do |option| %>
        <%= form_tag api_pay_path, class: 'payment-option' do %>
          <%= hidden_field_tag :payment_code, option.code %>
          <%= submit_tag "Pagar com #{option.code.split("_").last.capitalize}", class: 'button payment-option' %>
        <% end %>
      <% end %>
    <% else %>

      <% details[:options].each do |option| %>
        <%= link_to "Pagar com #{option.code.split("_").last.capitalize}", '#', class: 'show-credit-card-form button payment-option', data: { code: option.code, name: option.code.split("_").last.capitalize } %>
      <% end %>

      <div class="credit-card-form" style="display: none;">
        <div class="close">✕</div>
        <%= form_for :credit_card, :url => :api_pay do |f| %>

          <%= hidden_field_tag :payment_code, '' %>

          <fieldset>
            <legend>Dados do cartão <span id="card-name"></span></legend>

            <div class="row">
              <div class="large-4 columns">
                <label>Número do cartão</label>
                <%= f.text_field :number, :placeholder => "Digite apenas números" %>
              </div>
              <div class="large-4 columns">
                <label>Código de segurança</label>
                <%= f.text_field :security_code, :placeholder => "Digite apenas números" %>
              </div>
              <div class="large-4 columns">
                <label>Data de vencimento</label>
                <%= f.text_field :expiration, :placeholder => "mm/yyyy" %>
              </div>
            </div>
            <div class="row">
              <div class="large-4 columns">
                <label>Nome do titular do cartão</label>
                <%= f.text_field :holder_name, :placeholder => "Exatamente como está escrito no cartão" %>
              </div>
              <div class="large-4 columns">
                <label>CPF</label>
                <%= f.text_field :holder_cpf, :placeholder => "Apenas dígitos" %>
              </div>
              <div class="large-4 columns">
                <label>Telefone</label>
                <%= f.text_field :holder_phone, :placeholder => "Apenas dígitos" %>
              </div>
            </div>
          </fieldset>
          <% details[:options].each do |option| %>
            <fieldset class="installments" id="installments-<%= option.code %>" style="display: none;">
              <legend>Parcelamento <%= option.code.split("_").last.capitalize%> (<%= option.installments.description %>)</legend>
              <% option.installments.installments.each do |i| %>
                <div class="row">
                  <div class="large-6 columns">
                    <%= f.radio_button :installments, i.quantity, :id => "parcelas-#{option.code}-#{i.quantity}", class: 'parcelas' %>
                    <label for="parcelas-<%= option.code %>-<%= i.quantity %>">
                      <span style="display:inline-block; width: 100px;"><%= i.quantity.to_s.rjust(2, '0') %> x <%= number_to_currency(i.unitary_amount) %></span>
                      <span style="display:inline-block; width: 100px;">= <%= number_to_currency(i.total_amount) %></span>
                    </label>
                  </div>
                </div>
              <% end %>
            </fieldset>
          <% end %>

          <div class="row">
            <div class="large-12 columns">
              <button type="submit" class="button success small">Pagar</button>
              <button type="submit" class="button success small fill-in">Preencher</button>
            </div>
          </div>
        <% end %>
      </div>

    <% end %>

  <% end %>

</div>

app/views/checkout/api/boleto.html.erb
<div class="large-12 columns">
  <h1>Gerar boleto</h1>
  <%= link_to 'Clique aqui', @cart.url, :target => '_blank' %> para imprimir o boleto.
</div>

app/views/checkout/api/credit_card.html.erb
<div class="large-12 columns">
  <h1>Transação realizada</h1>
  O status da transação é: <strong><%= @cart.status %></strong>.
</div>

app/views/checkout/api/eft.html.erb
<div class="large-12 columns">
  <h1>Realizar transferência</h1>
  <%= link_to 'Clique aqui', @cart.url, :target => '_blank' %> para ser redirecionado ao site do banco e realizar a transferência.
</div>

app/views/checkout/form.html.erb
<div class="large-12 columns">

  <%= button_tag 'Mostrar formulário', id: 'show-form-fields-btn' %>

  <%= form_tag Akatus::Services::Transaction.form_url, target: '_blank', id: 'akatus-form' do %>

    <!-- Campos obrigatórios com detalhes da transação -->
    <!-- Email conta Akatus que receberá o valor da transação -->
    <%= hidden_field_tag 'email_cobranca', Akatus.config.email %>
    <!-- Este campo indica que o carrinho é gerenciado pela loja -->
    <%= hidden_field_tag 'tipo', 'CP' %>
    <!-- A moeda em que a transação será feita. Atualmente, o único valor aceito é BRL -->
    <%= hidden_field_tag 'moeda', 'BRL' %>

    <!-- Produtos do carrinho (é obrigatório haver pelo menos um produto) -->
    <% @cart.each_with_index do |item, idx| %>
      <!-- Identificador único do item (numérico ou texto) -->
      <%= hidden_field_tag "item_id_#{idx + 1}", item[:id] %>
      <!-- Descrição do item -->
      <%= hidden_field_tag "item_descr_#{idx + 1}", item[:title] %>
      <!-- "Me vê 3 dessas, por favor!" -->
      <%= hidden_field_tag "item_quant_#{idx + 1}", item[:quantity] %>
      <!-- "O quê? Só R$ 39,99? Que barato!" -->
      <%= hidden_field_tag "item_valor_#{idx + 1}", Akatus.format_number(item[:price]) %>
    <% end %>

    <!-- Comprador (opcional, mas útil para que o cliente não digite novamente todos os dados no carrinho da Akatus) -->
    <%= hidden_field_tag 'cliente_nome', 'Johny English' %>
    <%= hidden_field_tag 'cliente_cep', '01311300' %>
    <%= hidden_field_tag 'cliente_end', 'Av. Paulista' %>
    <%= hidden_field_tag 'cliente_num', '2000' %>
    <%= hidden_field_tag 'cliente_compl', 'Sala 10' %>
    <%= hidden_field_tag 'cliente_bairro', 'Bela Vista' %>
    <%= hidden_field_tag 'cliente_cidade', 'São Paulo' %>
    <%= hidden_field_tag 'cliente_uf', 'SP' %>
    <%= hidden_field_tag 'cliente_pais', 'BRA' %>
    <%= hidden_field_tag 'cliente_ddd', '11' %>
    <%= hidden_field_tag 'cliente_tel', '912345678' %>
    <%= hidden_field_tag 'cliente_email', 'email@cliente.com.br' %>

    <!-- Frete (sim, é uma "gambiarra", porque o frete deve ser especificado por produto, e não por carrinho) -->
    <!-- Cuidado: esse valor será multiplicado pela quantidade de items! -->
    <%= hidden_field_tag 'item_frete_1', Akatus.format_number(11.90) %>

    <!-- Desconto (deve ser um número negativo!) -->
    <%= hidden_field_tag 'extras', Akatus.format_number(-10.00) %>

    <%= submit_tag 'Clique aqui para testar o pagamento via formulário web com a Akatus', class: 'button' %>

  <% end %>

</div>

app/views/checkout/javascript.html.erb
<div class="large-12 columns">
  <p>Ops!, em construção.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Akatus Demo</title>
  <%= stylesheet_link_tag    "application", media: "all"  %>
  <%= javascript_include_tag "application", "vendor/modernizr" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body class="<%= controller_name %> <%= action_name %>">

  <!-- Nav Bar -->

  <div class="row">
    <div class="large-12 columns">
      <div class="nav-bar right">
        <ul class="button-group">
          <li><%= link_to 'API', api_path, class: 'button' %></li>
          <li><%= link_to 'HTML (Formulário)', form_path, class: 'button' %></li>
          <li><%= link_to 'JavaScript', javascript_path, class: 'button' %></li>
        </ul>
      </div>
      <%= link_to root_path do %>
        <h1>Akatus <small>demo</small></h1>
      <% end %>
      <hr />
    </div>
  </div>

  <!-- End Nav -->

  <div class="row">
    <%= yield %>
  </div>

</body>
</html>

app/views/welcome/index.html.erb
<div class="large-12 columns">
  <p>Escolha uma das opções no menu acima.</p>
</div>